version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    container_name: reporteadorPatrones
    environment:
      POSTGRES_USER: tander
      POSTGRES_PASSWORD: reporteador
      POSTGRES_DB: reporteadorDB
    volumes:
      - ./postgrest:/var/lib/postgresql/data
    ports:
      - "5432:5432"
